#!/usr/bin/env node
// PreToolUse hook: blocks writes to protected files.
// Exit 2 tells Claude Code to deny the tool call; stderr is shown as the reason.
//
// Payload is parsed with Node rather than jq, which is not installed on this
// machine — the previous shell version silently exited 0 for every write.

import { relative, resolve, sep } from 'node:path';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

/**
 * Each entry is tested against the repo-relative path using forward slashes.
 * `dir` matches the directory and everything under it; `exact` matches the
 * basename anywhere in the tree; `suffix` matches the tail of the path.
 */
const PROTECTED = [
    { kind: 'exact', value: '.env', reason: 'contains secrets' },
    { kind: 'suffix', value: '.env.local', reason: 'contains secrets' },
    { kind: 'suffix', value: '.env.production', reason: 'contains secrets' },
    { kind: 'exact', value: 'package-lock.json', reason: 'is generated by npm' },
    { kind: 'dir', value: '.git', reason: 'is git internal state' },
];

let raw = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => (raw += chunk));
process.stdin.on('end', () => {
    let filePath;
    try {
        const payload = JSON.parse(raw);
        filePath = payload?.tool_input?.file_path ?? payload?.tool_response?.filePath;
    } catch {
        process.exit(0); // malformed payload — nothing to check
    }

    if (!filePath) process.exit(0);

    // Normalize to repo-relative, forward-slashed, for stable matching.
    const target = resolve(filePath);
    const rel = relative(projectRoot, target).split(sep).join('/');

    // Outside the repo entirely — not ours to guard.
    if (rel.startsWith('../')) process.exit(0);

    const segments = rel.split('/');
    const basename = segments[segments.length - 1];

    for (const rule of PROTECTED) {
        const hit =
            (rule.kind === 'exact' && basename === rule.value) ||
            (rule.kind === 'suffix' && basename.endsWith(rule.value)) ||
            (rule.kind === 'dir' && segments.includes(rule.value));

        if (hit) {
            process.stderr.write(`BLOCKED: refusing to write ${rel} — it ${rule.reason}.\n`);
            process.exit(2);
        }
    }

    process.exit(0);
});
